services: 
  back-end: 
    image: "kieran3410/crypto-dashboard:back-end"
    ports:
      - "8000:80"
  front-end:
    image: "kieran3410/crypto-dashboard:front-end"
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    
