version: "3.8"
services: 
  back-end: 
    build: "Backend/."
    ports:
      - "8000:80"
  front-end:
    build: "Front\ End/crypto-dashboard/."
    ports:
      - "3000:3000"
    depends_on:
      - back-end
    
